### ISSUE TITLE
validation result of nested object contains ConstraintCondition lost field name

### ISSUE THREAD

**Issue by sis-yoshiday** [making/yavi#127]
Hi

`ConstraintViolation.name()` returns unexpected value in some situation.

1. validation for nested object
2. descendant object validator has `ConstraintCondition`

**Comment by sis-yoshiday** [comment]
this problem reproduce in below test case. 

https://github.com/making/yavi/pull/128

**Comment by making** [comment]
@sis-yoshiday Thanks for your report.

In what version does it happen?
Did it work in previous versions?

**Comment by sis-yoshiday** [comment]
@making 
It reproduced current develop branch. (is 0.5.1?)
I haven't tried  in `0.6.0` yet.

**Comment by making** [comment]
I have confirmed that the test fails even with 0.6.0.

**Comment by making** [comment]
@sis-yoshiday YAVI 0.6.1 is out
