### ISSUE TITLE
Fail fast mode support?

### ISSUE THREAD

**Issue by lonre** [making/yavi#140]
allows to return from the current validation as soon as the first constraint violation occurs

**Comment by making** [comment]
No, YAVI is designed to collect all violations

**Comment by lonre** [comment]
Can we give this option for users?

**Comment by making** [comment]
What’s the usecase?
I’m reluctant about it. 
Again YAVI is designed to collect all violations, so the support of it makes code base dirty.

**Comment by lonre** [comment]
Just like https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#section-fail-fast

As we provide api for our customers, we only show one toast tip, so there is no need to collect all violations for this case.

**Comment by making** [comment]
Thanks for the link.
Do you think the evaluation order of constraints matters?

**Comment by lonre** [comment]
> Thanks for the link.
> Do you think the evaluation order of constraints matters?

Hi, the evaluation order doesn't matter for me

**Comment by making** [comment]
@lonre 
You can try the feature using `0.8.0-SNAPSHOT`
https://github.com/making/yavi#usage

```java
Validator<User> validator = ValidatorBuilder.<User> of()
    .constraint(User::getName, "name", c -> c.notNull()
        .lessThanOrEqual(20))
    .constraint(User::getEmail, "email", c -> c.notNull()
        .greaterThanOrEqual(5)
        .lessThanOrEqual(50)
        .email())
    .constraint(User::getAge, "age", c -> c.notNull()
        .greaterThanOrEqual(0)
        .lessThanOrEqual(200))
    .failFast(true) // <-- Enable the fail fast mode
    .build();

// or

Validator<User> failFastValidator = validator.failFast(true); // <-- Switch to the fail fast mode
```

I would appreciate it if you could give it a try and give me feedback.

**Comment by lonre** [comment]
Wow, it is quit awesome.

will try it this afternoon, thanks for your work.

**Comment by lonre** [comment]
Hi @making 

already tried against 0.8.0-SNAPSHOT, it works like a charm, thanks for your work.
