### ISSUE TITLE
Support unique lists

### ISSUE THREAD

**Issue by juergenzimmermann** [making/yavi#153]
It would be nice to validate that a list must contain unique elements, and isn't allowed to contain any duplicates.

**Comment by making** [comment]
Why not use Set?

**Comment by juergenzimmermann** [comment]
List offers ordering, and Set doesn't. When you insert a new element the ordering isn't preserved in a (Hash) Set, but a list's default insert (at the end) preserves the ordering which is often a must in GUIs.

**Comment by making** [comment]
I would use `LinkedHashSet`

**Comment by making** [comment]
Is there a use case where `List` type is required and `LinkedHashSet` cannot be used?

**Comment by juergenzimmermann** [comment]
`LinkedHashSet` doesn't provide direct access like List's `get(int index)`.

**Comment by juergenzimmermann** [comment]
Hibernate Validator addresses this feature in https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/UniqueElements.html

**Comment by making** [comment]
@juergenzimmermann OK, will implement it. or you can also send a pr :)

**Comment by making** [comment]
will be shipped in 0.8.3
