### ISSUE TITLE
Kotlin custom error message ignores arguments() override

### ISSUE THREAD

**Issue by SimonBalling** [making/yavi#165]
Hi
Im trying to get yavi to display a custom error message but I dont seem to be able to get custom arguments to work.
Its either broken for kotlin or Im doing something wrong.
This is my code
```
@Service
class TagTagValidator : PassModelValidation<TagTag> {
    override fun buildValidator(validatorBuilder: ValidatorBuilder<TagTag>) =
        validatorBuilder.apply {
            konstraint(TagTag::name) {
                notNull()
                    .notBlank()
                    .predicate(ValidTagConstraint())
            }
        }
}

class ValidTagConstraint : CustomConstraint<String?> {

    private val actualCount = 0

    private val maxCount = 50

    override fun arguments(): Array<Any> {
        return arrayOf(this.maxCount, this.actualCount)
    }

    override fun messageKey(): String {
        return ""
    }

    override fun defaultMessageFormat(): String {
        return """The tag "{3}" may not be longer than {1} bytes. length is {2}"""
    }

    override fun test(tag: String?): Boolean {
        return (tag?.toByteArray()?.count() ?: 0) <= maxCount
    }

}
```

If I set a breakpoint into the override class it wont stop there

**Comment by making** [comment]
@SimonBalling Thanks for the report.
The current implementation is that custom arguments only work when using `constraintOnTarget`. It should work even if it is specified as predicate as you suggest.

**Comment by SimonBalling** [comment]
Is there a konstraintOnTarget? I only seem to be able to find Condition, Group and Object

**Comment by making** [comment]
No, `konstraint` methods will be deprecated in the next release in favor of [new DSL](https://github.com/making/yavi/pull/152).
Anyway I will fix this bug.

**Comment by SimonBalling** [comment]
Great, thanks

**Comment by making** [comment]
Hi @SimonBalling 

I have merged a breaking change to this issue. I believe this change is more suitable for your original request. 

https://github.com/making/yavi/pull/178/files#diff-fae75941be7141806bd912a73fec5e4e9371789e3e5c6d4cfa6b6d1462c9315c
