### ISSUE TITLE
Dynamic error messages

### ISSUE THREAD

**Issue by sergtitov** [making/yavi#169]
Please add support for custom dynamic error messages, for example:

In my validator I call The API that returns a list of supported values and I want to include that list in the error message:

```
var validator = ValidatorBuilder.<MyObject>of()
                .constraint(MyObject::type, "type", x -> x.notBlank().predicate(
                        type -> myApi.getTypes().contains(type),
                        ViolationMessage.of(<How do I include the list of supported types from myApi.getTypes() here?>)))
                .build();
```

Alternatively, I tried to implement `CustomConstraint` as described in https://yavi.ik.am/#creating-a-custom-constraint, but could not make it return dynamic value from `arguments()`:

   ```
@Override
    public Object[] arguments() {
        return new Object[] { <How do I return a result of the call myApi.getTypes() here> };
    }

    @Override
    public String defaultMessageFormat() {
        return "Type value \"{0}\" must be one of: \"{1}\".";
    }
```

    @Override
    public String messageKey() {
        return "type";
    }

    @Override
    public boolean test(String type) {
        return myApi.getTypes().contains(type);
    }

**Comment by making** [comment]
I think it is related to https://github.com/making/yavi/issues/165

Can you try 0.9.0-SNAPSHOT? It's available in the following repository

```xml
<repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshots</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

**Comment by sergtitov** [comment]
@making I could not find in 0.9.0 how to create dynamic messages, can you point me to an example please?

`Object[] arguments()` allows only defining arguments at validator "build time" - when validator is created but not when `validate` is called. So I can't make the message contain dynamic values - API call results (at the time of validation) or values from the object being validated.

For example, I have a collection of elements and I want to check they are all unique and if found 2 equivalent ones, I want to add them to the violation message. How can I achieve that?

**Comment by making** [comment]
@sergtitov Here is the enhancement I can think of.
https://github.com/making/yavi/commit/10d71e2d5d08c2e3a5f7167e1157ca5c2b540379 
Do you think this will work for you as well?
