### ISSUE TITLE
Using YAVI as a JPMS module generates warning during Maven build

### ISSUE THREAD

**Issue by duponter** [making/yavi#171]
When using YAVI as a dependency in a JPMS compliant application, following warning is issued by Apache Maven 3.8.1 during compilation (using Java versions 11 and 17, vendor: Temurin)

> [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ matis-infrastructure ---
> [INFO] Required filename-based automodules detected: [yavi-0.8.3.jar]. Please don't publish this project to a public artifact repository!

Additionally to add the YAVI dependency in the project's pom file, an entry has to be added to the project's module-info.java.
`requires yavi;`

Issue #160 suggests that you're planning full module support in the future, it is fairly easy to prevent this warning while awaiting the actual module support.
It merely requires to add some manifest configuration to the default maven-jar-plugin configuration. (I will submit a PR very soon)
Following entry will be added to the generated manifest.mf: `Automatic-Module-Name: am.ik.yavi`
If preferred, another module name can be inserted here.

After applying these changes, the YAVI entry in module-info.java needs to be changed to:
`requires am.ik.yavi;`

**Comment by making** [comment]
Fixed via gh-172
