### ISSUE TITLE
Why limit of 10 arguments for combining and splitting instead of 16?

### ISSUE THREAD

**Issue by duponter** [making/yavi#175]
YAVI supports up to 16 arguments to validate:
`am.ik.yavi.arguments.Arguments16Validator` exists, but the arguments combining and splitting functionality only supports up to 10 Validators (`Arguments10Combining` and `Arguments10Splitting`). What's the reason for this limitation?

Same question applies for functions:
`am.ik.yavi.fn.Function16` exists, but only up to 10 Validations can be combined via `Combining10`.

**Comment by making** [comment]
Need for Combining 14 is a signal for your design rethink. Normally you shouldn't need that much N. Also keep in mind that chaining too many combine methods will create a lot of objects and lead to worse performance.
