### ISSUE TITLE
Replace konstraint extensions by a validator Kotlin DSL

### ISSUE THREAD

**Issue by sdeleuze** [making/yavi#18]
In order to provide a more idiomatic Kotlin experience, I am wondering if we could replace `konstraint` extensions introduced by #16 (I don't really like this kind of `k` prefixed to be honest) by a Kotlin DSL that would isolate more the Kotlin API from the Java one. I need to give it more thoughts but my initial proposal is the following:

```
val validator = validator<User> {
     constraint(User::name) {
          notNull()
          lessThanOrEqual(20)
     }
     constraint(User::email) {
          notNull()
          greaterThanOrEqual(5)
          lessThanOrEqual(50) //
          email()
     }
     constraint(User::age) {
          notNull()
          greaterThanOrEqual(0)
          lessThanOrEqual(200)
     }
}
```

Any thoughts? If you like it I can probably try to craft a PR.

**Comment by making** [comment]
The motivation of #16 was that it was frustrating to find a method for Kotlin from a lot of candidates. Changing method names worked for me.
If your suggestion works too, it would be great to make this library more Kotlin idiomatic.

My another concern is the maintenability of the isolated API for Kotlin.
This library was not originally designed for Kotlin and started to support it with minimal efforts.
I'm not confident to keep on updating the API.

But I'd really like to see how the DSL will be implemented.

**Comment by sdeleuze** [comment]
The question of the maintainability of the Kotlin API is a good one, and I would also add another point that I have in mind for Kofu: multiplatform validation to be able to do same checks on server side via Kotlin/JVM and client side with Kotlin/JS.

This will likely require a Kotlin MP library like https://github.com/konform-kt/konform so I need to think more about that before asking advanced support for Kotlin here.

**Comment by hartmut-co-uk** [comment]
+1 for the Kotlin DSL, e.g. the DSL of https://github.com/konform-kt/konform looks very clean. 
(Or would this be too big of a break with the Java compatibility..?)

**Comment by making** [comment]
@hartmut-co-uk Are you willing to propose a pull request?

**Comment by hartmut-co-uk** [comment]
let me try to make time! (might not be within the next 2 weeks)

**Comment by hartmut-co-uk** [comment]
I've made a start -> https://github.com/making/yavi/pull/152

Please let me know what you think, seems this won't be a small feat to cover the vast YAVI capabilities.. :-)

**Comment by making** [comment]
Supported by 0329aa47f67c4071adc3cc576f9287faaddbdde7 🎉
