### ISSUE TITLE
Support on Kotlin Multiplatform?

### ISSUE THREAD

**Issue by iamcyw** [making/yavi#181]
Hello,
I have a multiplatform project and there are some objects that need to be verified in the multiplatform module. So is there a way to use yavi or support?

**Comment by making** [comment]
I'm not familiar with kotlin multiplatform. But YAVI is currently just a java library that can be used with Kotlin. so I don't think it can be used in the multiplatform module.

**Comment by iamcyw** [comment]
So do you think there will be any problems with migrating to kotlin rewrites, and can I try that?

**Comment by making** [comment]
Technically I don’t think there is any blocker to rewrite yavi in kotlin though no plan to do it.
