### ISSUE TITLE
Support conditional constraint

### ISSUE THREAD

**Issue by making** [making/yavi#2]
@enricosecondulfo Thanks for the feedback in https://github.com/spring-projects/spring-fu/issues/83#issuecomment-418145689

Personally, I prefrer to define different validators for create and update or have different data class for create and update for explicitly.  I had a bad experience to be cofused by abuse of grouping constraints with Bean Validation. That's why I scoped it out at first time.

But I could support conditional constraint with more functional style.

The idea in my mind is as following

```java
ConstraintGroup group = ConstraintGroup.of("update");

Validator<User> validator = Validator.builder(User.class) //
		.constraintOnCondition(group.toCondition(), //
				b -> b.constraint(User::getName, "name",
						c -> c.lessThanOrEqual(10)))
		.build();

validator.validate(user, group);
```

Flexible conditons can be written by lamda expressions as well

```java
ConstraintGroup group = ConstraintGroup.of("update");

Validator<User> validator = Validator.builder(User.class) //
		.constraintOnCondition((user, cg) -> {
			String name = cg.name();
			return name.equals("update") || name.equals("delete");
		}, b -> b.constraint(User::getName, "name", c -> c.lessThanOrEqual(10)))
		.build();

validator.validate(user, group);
```

**Comment by enricosecondulfo** [comment]
@making i love your idea

**Comment by making** [comment]
Hi @enricosecondulfo 
yavi 0.0.18 supported [conditional constraints](https://github.com/making/yavi#conditional-constraint) :)

**Comment by enricosecondulfo** [comment]
@making Thank you so much
