### ISSUE TITLE
Enums validation

### ISSUE THREAD

**Issue by ffroliva** [making/yavi#207]
I need to validate if a given Enum class is not null for example. I could not find in the documentation how to handle this scenario. What should be considered the best practice in this situation?

**Comment by making** [comment]
@ffroliva 
Enum fields can be validated by constraints on [Object](https://yavi.ik.am/#object).
- `notNull`
- `password`
- `oneOf`
- `equalsTo`
are supported.
You may need the explicit `_object` instead of `constraint` to avoid ambiguous type inference.

**Comment by ffroliva** [comment]
Thank you. I will have a look at that.

Em qua., 9 de fev. de 2022 às 02:45, Toshiaki Maki ***@***.***>
escreveu:
