### ISSUE TITLE
formatting the error message

### ISSUE THREAD

**Issue by rodrigodevelms** [making/yavi#21]
I'm trying to format the error output as follows:
```
{
   field : fieldName
   message: List of Message
}
```
for exemple:
```
{
    field : Name
    messagem : {
           "The Name field is required"
           "The Name field must contain between 4 and 100 characters"
    }

    // others fields / messages
}
```

What I've done so far:
```

fun errorMsg(T: ConstraintViolations): List<String> {
    val errorList = mutableListOf<String>()
    T.forEach { errors -> errorList.add(errors.message()) }
    return errorList
```
But I looked in the documentation and found nothing on how to capture the field that is in error.
There's something like:
`
ConstraintViolations.forEach {error -> error.field ()}`

**Comment by making** [comment]
What’s the problem?

**Comment by making** [comment]
I'm closing this issue. If you have further questions, feel free to reopen
