### ISSUE TITLE
Replace validation Group by a validation context 

### ISSUE THREAD

**Issue by deblockt** [making/yavi#213]
My project should be available for many country and validation rules can be different for each contry.

For exemple: 
``` java
public class User {
    public String firstName;
    public String lastName;


    private static final ValidatorBuilder<User> VALIDATOR = ValidatorBuilder.<User>of()
            .constraint(User::getFirstName, "firstName", Constraint::notNull)
            . constraintOnCondition((user, group) -> isItalian(), b.constraint(User::LastName, "lastName", Constraint::notNull))
}
```

In this example the lastName is mandatory only for Italian. 
Actually using yavi I can not implement the `isItalian` function since I need to read an HTTP header to know if it's italian or not. 

so I think that have a context instead of a group can be fine to solve this issue.
We can do something like that:
``` java
. constraintOnCondition((user, context) -> context.get("countryCode").equals("IT"), b.constraint(User::LastName, "lastName", Constraint::notNull))
```

Another solution it to create a group by country, but i can can hard to maintain. If I already use a group `EDIT` `CREATE`, I will have `EDIT_FR`, `CREATE_FR`, `EDIT_IT`, `CREATE_IT`, I think that It can be hard to manage.

**Comment by making** [comment]
Having a "context" in a static validator looks wierd to me.
You can dynamically define the Validator wherever you can access the header.

I would define a class with `countryCode` field and create a crossfield constraint.

```java
public class User {
	private String firstName;

	private String lastName;

	private String countryCode;

	private static final Validator<User> VALIDATOR = ValidatorBuilder.<User>of()
			.constraint(User::getFirstName, "firstName", Constraint::notNull)
			.constraintOnCondition((user, group) -> "IT".equals(user.getCountryCode()),
					b -> b.constraint(User::getLastName, "lastName", Constraint::notNull))
			.constraintOnCondition((user, group) -> "FR".equals(user.getCountryCode()),
					b -> b.constraint(User::getLastName, "lastName", Constraint::notNull))
			.build();
// ...
}
```

**Comment by duponter** [comment]
We are using the dynamic `ConstraintGroup` approach to solve these kind of problems.

However, we've added custom `ConstraintGroup` implementations to keep duplication of validators to a minimum
```java
private static final Validator<User> VALIDATOR = ValidatorBuilder.<User>of()
		.constraint(User::getFirstName, "firstName", Constraint::notNull)
		.constraintOnGroup(ConstraintsGroups.anyOf("IT", "FR"),
				b -> b.constraint(User::getLastName, "lastName", Constraint::notNull))
		.build();
```

These are the custom `ConstraintGroup` implementations we currently define:
```java
public static ConstraintGroup anyOf(ConstraintGroup... groups) {
    return new ConstraintGroup() {
        @Override
        public String name() {
            return Arrays.stream(groups)
                .map(ConstraintGroup::name)
                .collect(Collectors.joining("/"));
        }

        @Override
        public <T> ConstraintCondition<T> toCondition() {
            return (target, group) -> Arrays.stream(groups)
                .map(ConstraintGroup::toCondition)
                .anyMatch(condition -> condition.test(target, group));
        }
    };
}

public static ConstraintGroup not(ConstraintGroup group) {
    return new ConstraintGroup() {
        @Override
        public String name() {
            return "NOT-" + group.name();
        }

        @Override
        public <T> ConstraintCondition<T> toCondition() {
            return (target, other) -> group.toCondition().negate().test(target, other);
        }
    };
}
```

This might be a possible extension to the current `ConstraintGroup` interface?

**Comment by making** [comment]
@duponter It looks convenient. Pull requests are welcome.

**Comment by ffroliva** [comment]
I agree

Em qui., 17 de fev. de 2022 às 10:18, Toshiaki Maki <
***@***.***> escreveu:

**Comment by deblockt** [comment]
Hi, Thanks for all theses information. 

@making The proposal is not to add a static context on validator building, but to replace groups by a context when call the `validate` function.

``` java 
public class User {

    public String firstName;
    public String lastName;

    private static final Validator<User> VALIDATOR = ValidatorBuilder.<User>of()
            .constraint(User::getFirstName, "firstName", Constraint::notNull)
            // here the context var come from the `.validate` call
            .constraintOnCondition((user, context) -> context.get("country").equals("IT"), b -> b.constraint(User::getLastName, "lastName", Constraint::notNull))
            .build();

    public User(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    // when we call .validate we can initialize the context instead of create a group
    public ConstraintViolations validateForCountryContextMode(String country) {
        return VALIDATOR.validate(new User("foo", null), Context.from(Map.of("country", country)));
    }
}
```

The @duponter solution is quite close to the context. The main difference is that instead have a context with key and value, the value are on the name of the group. If the group is created dynamically (by name concatenation), I'm not sure that is more readable that have a context. 

The context gives more flexibility, by example you can imagine manage feature flipping using the context. For example you can imagine enable or disable constraint in function of a configuration. We work with many feature toggle on my project, and it could help us.

Thank you for your reactivity

**Comment by making** [comment]
@deblockt I just sent a pr (#216) to introduce `ConstraintContext`.
I've tried backwards compatibility, but it may break the code of advanced users like @duponter . 
I would appreciate your feedbacks.

**Comment by duponter** [comment]
Our code with the ConstraintGroups is still experimental. This is a welcome addition to the library. Therefore, we will update our code to use the context instead of the groups.
