### ISSUE TITLE
Change Message Formatter globally

### ISSUE THREAD

**Issue by ffroliva** [making/yavi#217]
Item 3.9. Message Formatter in the documentation describes how to replace the default message formatter. Is there a way to change the message formatter globally so that it would not be necessary to replace me message formatter in each validator?

**Comment by making** [comment]
Simply create a utility class like bellow

```java
public class MyBuilder {
	public static <T> ValidatorBuilder<T> builder() {
		return ValidatorBuilder.<T>of()
				.messageFormatter(new MyMessageFormatter());
	}
}
```

or you can also use [ValidatorFactory](https://yavi.ik.am/#managing-validatorbuilder-in-an-ioc-container).
