### ISSUE TITLE
Support for enum types on ValidationBuilder

### ISSUE THREAD

**Issue by pnowy** [making/yavi#225]
Hi,

maybe I missed something but it looks like there is no native Enum support for `ValidationBuilder.constraint()`

Did I miss something or there is not that kind of support yet?

Thanks

**Comment by making** [comment]
https://github.com/making/yavi/issues/207
Duplicate?

**Comment by pnowy** [comment]
Indeed - that's the same issue :) 

So example if somebody would have the same problem like me simple example: 
```
...
._object(User::getStatus, "status", c -> c.notNull())
...
```

Maybe it would be nice add to the documentation (or maybe I missed that) the case with enums.
