### ISSUE TITLE
Validate collection containing null values

### ISSUE THREAD

**Issue by voodoo-patch** [making/yavi#226]
Hello,
i like the approach of this library, but i'm not able to figure out how to validate null values in a collection.
I've tried to use the _notNull_ predicate but does not seem to work.

I've created a small example to reproduce what i'm trying to achieve at this link https://onecompiler.com/java/3xwau4dma.

Thanks in advance for any suggestion.

**Comment by making** [comment]
It looks like a bug. If you set an empty string, it works as expected.

**Comment by voodoo-patch** [comment]
I found a workaround to check on null values by using a custom constraint:



    class CollectionContainsNullConstraint implements CustomConstraint<List<String>> {

        @Override
        public boolean test(List<String> collection) {
            return collection != null && !collection.stream().anyMatch(Objects::isNull);
        }

        @Override
        public String messageKey() {
            return "collection.containsNull";
        }

        @Override
        public String defaultMessageFormat() {
            return "\"{0}\" must not contain null values";
        }
    }

I would've fixed the bug but still can't spot the point that requires editing. Any suggestion or guidance is appreciated

**Comment by alexshavlovsky** [comment]
Actually there is a test case exclusion for this bug dated 23.08.2018:
https://github.com/making/yavi/blob/develop/src/test/java/am/ik/yavi/core/AbstractCollectionValidatorTest.java#L112
