### ISSUE TITLE
Support extending validator

### ISSUE THREAD

**Issue by jolangloys** [making/yavi#23]
It would be nice to be able to extend an existing validator to apply it on the root of the current validated object, in order to use a validator created for a super type (or just to create a hierarchy of validator)

For example, let's say I have two classes like these :
```java
public class Person {
    private String name;

    public static final validator = ValidatorBuilder.of(Person.class)
                            .constraint(Person::getName, "name", Constraint::NotNull)
                            .build();

    // Etc...
}


public class Employee extends Person {
    private String serviceId;

    public static final validator = ValidatorBuilder.of(Employee.class)
                            // Apply the validator Person.validator here
                            .constraint(Employee::getServiceId, "service", Constraint::NotNull)
                            .build();

    // Etc ...
}
```
In this case, the work around I have come out with is `.nest(Person.class::cast, "person", Person.validator)` but it's not super readable. and I end up with a prefix "person.Xxx" which doesn't really mean anything.
Something like `.extends(Person.validator)` would be perfect

**Comment by making** [comment]
@jolangloys Thanks for your feedback. That's what I didn't come up with.
Introduction `extends` might cause complex situations like multiple inheritance.

I'm thinking to add `delegate` or `copyOf` to support your case.

**Comment by making** [comment]
@jolangloys 
I've added `ValidatorBuilder.cast` method so that you can share `Person` 's validator with `Employee`. This should be simpler than extending validator.

Please take a look at a test case.
https://github.com/making/yavi/commit/3c56a4c054b089a78c048421cca0891215f7560c

**Comment by making** [comment]
Sorry I'll revert https://github.com/making/yavi/commit/3c56a4c054b089a78c048421cca0891215f7560c
This implementation mutates `ValidatorBuilder` ...

**Comment by making** [comment]
also added `clone` method.

See https://github.com/making/yavi/commit/82c6990f76ab4011560389a1fa978415af4186db

**Comment by jolangloys** [comment]
Thank you for your answer and work.

But the problem here is that we usually don't retain instance of `ValidatorBuilder` but we build them directly into `Validator` so the clone() and cast() methods won't help in this case.

I don't really think multiple inheritance of validator should be a problem. However, I can see the problem extracting internal attributes from the `Validator` class.

I can suggest you a compromise : create a method in the `Validator` class `ValidatorBuilder<S extends T> extend(Class<T> clazz)` (or whatever the name) in order to obtain a `ValidatorBuilder` on a sub class of an existing validator.

**Comment by making** [comment]
@jolangloys I also considered to add `mutate` method to `Validator`. The usage looks like 

```java
Person.validator.mutate() // returns ValidatorBuilder
               .cast(Employee.class)
               .constraint(Employee::getServiceId, "service", Constraint::NotNull)
               .build();
```

pretty close to your suggestion.

The problem here is the cross reference between Validator <-> ValidatorBuilder I've ever resolved in #7 .

If you have any more idea that doesn't have the cross reference, suggestion or PR is welcome.

**Comment by jolangloys** [comment]
Hello,

It's up to you, but I don't think that having a class and its own builder tight coupled with circular dependency is a problem. If you change one, you'll always need to change the other. To be honest, I have been surprise to find them in different package.

However, If you want to keep the pure unidirectional relationship, my first  suggestion will be better then. For me, You'll then have two way of accomplishing this:
- Extract the attributes of the Validator. For example use package private methods to and an intermediate class
- Add an attributes to Validator & ValidatorBuilder like includedValidator which will be another Validator or a Set of Validator which will be called at validation time.

**Comment by making** [comment]
I'm closing this issue. Feel free to reopen it if you have any further comment.
