### ISSUE TITLE
Does not pass given value when validating email address

### ISSUE THREAD

**Issue by runeflobakk** [making/yavi#246]
Somewhat similar issue as #240, so I am keeping this short :) 

The [documentation](https://yavi.ik.am/#email) for the email-validator specifies the `{1}`-argument as the given value, but it is not interpolated into the message.

```java
var validator = ValidatorBuilder.<String>of()
        .constraint((String email) -> email, "email",
                l -> l.email().message("{0} must be a valid email address, but was '{1}'"))
        .build();

var violation = validator.validate("@example.com").get(0);
assertThat(violation.message(), is("email must be a valid email address, but was '@example.com'"));
```

```
java.lang.AssertionError: 
Expected: is "email must be a valid email address, but was '@example.com'"
     but: was "email must be a valid email address, but was {1}"
```

Thought I'd also mention that the documentation for email-validator seems to be a little bit "off" as well, as it specifies the default message format as `"{0}" must match {1}`, but it does not make much sense to say `"email" must match @example.com`. However, the default message format seems to actually be `"{0}" must be a valid email address`, which is all fine, though it does not include the given value.

Thanks!

**Comment by making** [comment]
It’s a document bug.
Is there anything wrong with what you want to achieve?

**Comment by runeflobakk** [comment]
Ah, yes, I would like to include the given value in the message, but it is not included in the default message, nor if I override the message to include {1}.

**Comment by runeflobakk** [comment]
I should have included the assertion error. I have updated the issue.

**Comment by runeflobakk** [comment]
Oh... I was not aware of that gotcha with `MessageFormat`. Then it works as expected! Thank you very much!
