### ISSUE TITLE
Add validation for Apache POI 

### ISSUE THREAD

**Issue by ffroliva** [making/yavi#250]
I am currently working in a project where [Apache POI](https://poi.apache.org/) is the input source of data. It would be interesting if I could validate the a workboot sheet from the source (rows and cells) without having to do any major transformation. The whole idea is to eliminate the amount of loops I would need to do in order to transform the data into my model data. As consequence I would save memory and CPU usage. I am not sure if this is beyond the  scope of the project. Maybe the project could have a sub-module like `yavi-poi` or something similar if associating the dependencies is very project specific.

Let's take the following data as an example:

Name | MyInteger | MyDouble | MyDate
-- | -- | -- | --
A | 1 | 1.1 | 19/05/2022
B | 2 | 2.2 | 20/05/2022
C | 3 | 3.3 | 21/05/2022
D | 4 | 4.4 | 22/05/2022

The first part of the problem is to resolve the "Headers".

The second part is to resolve the field types. The headers determine the cell type:

- Name = String
- MyInteger = Integer
- MyDouble= Double
- MyDate = LocalDate
 
What do you think? Does it make sense? Comments on the idea would be highly appreciated.

**Comment by making** [comment]
I have no plan to add built-in constraints that  use other dependencies.
Please create custom constraints.

**Comment by RhyLove** [comment]
If someone used this against hacking into your phone and gaining control and access to all your information, how would someone go about erasing or getting rid of this?
