### ISSUE TITLE
Check if a given a list of numers are in order

### ISSUE THREAD

**Issue by ffroliva** [making/yavi#251]
Is there a validation that checks if a given list `List.of(1,2,3,4,5)` is in order or should a build a custom validator for that?

**Comment by making** [comment]
There is no such built-in constraint.

**Comment by making** [comment]
If the order of the collections is important, I would recommend that you try using a SortableSet instead of checking with validation.

**Comment by ffroliva** [comment]
The point is, my input data needs to came ordered by nature, otherwise I
should consider it invalid. Having a validator that looks if integers or
any object is its natural ordered would be an interesting validation to be
added in the framework in the future. That's just a thought.

**Comment by making** [comment]
I don't think it's a good design to check the order with validation. You should use the appropriate data structure.
I don't want to encourage such a design with YAVI.
