### ISSUE TITLE
Consider adding IntegerConstraint.range 

### ISSUE THREAD

**Issue by ffroliva** [making/yavi#284]
I am currently trying to validate if a given Integer is either 0 or 1. IntegerConstraint doesn't have a range validation. I believe this would be a handy constraint.

**Comment by making** [comment]
It should be added not only on integer but also on all number types.
Please send a pr.

**Comment by ffroliva** [comment]
Google guava has a good implementation that handles range. Would it be of interest to add a dependency on libraries such as google guava?

https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/collect/Range.html

To add this range functionality we would need to implement something similar.

Currently, I am creating custom constraints and applying the range validation using guava.

**Comment by ffroliva** [comment]
So I believe we would need to create the following constraints:

<html>
<body>


(a..b) | {x \| a < x < b} | open
-- | -- | --
[a..b] | {x \| a <= x <= b} | closed
(a..b] | {x \| a < x <= b} | openClosed
[a..b) | {x \| a <= x < b} | closedOpen
(a..+∞) | {x \| x > a} | greaterThan
[a..+∞) | {x \| x >= a} | atLeast
(-∞..b) | {x \| x < b} | lessThan
(-∞..b] | {x \| x <= b} | atMost
(-∞..+∞) | {x} | all


</body>
</html>

(a..b)	{x | a < x < b}	[open](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/Range.html#open(C,C))
[a..b]	{x | a <= x <= b}	[closed](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/Range.html#closed(C,C))
(a..b]	{x | a < x <= b}	[openClosed](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/Range.html#openClosed(C,C))
[a..b)	{x | a <= x < b}	[closedOpen](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/Range.html#closedOpen(C,C))
(a..+∞)	{x | x > a}	[greaterThan](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/Range.html#greaterThan(C))
[a..+∞)	{x | x >= a}	[atLeast](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/Range.html#atLeast(C))
(-∞..b)	{x | x < b}	[lessThan](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/Range.html#lessThan(C))
(-∞..b]	{x | x <= b}	[atMost](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/Range.html#atMost(C))
(-∞..+∞)	{x}	[all](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/collect/Range.html#all())

**Comment by making** [comment]
`greaterThan`, `atLeast`, `lessThan`, `atMost` are already provided. I don't think `all` makes sense
