### ISSUE TITLE
Delete Annotation Processor support

### ISSUE THREAD

**Issue by making** [making/yavi#290]
after #289

**Comment by odrotbohm** [comment]
Can you elaborate why you'd want to remove the annotation processor? I am wondering, as the AP-generated code was used as counterargument to my suggestion in #269. So, why would you drop that support?

I just came back here to see what the current state of affairs was, was thinking about suggesting providing a type-level annotation (like `@BeanConstraints`), that'd essentially work like the `@ConstraintTarget` target annotation but without actually having to annotate each method but rather discover them in the AP by following the Java Beans spec.

**Comment by making** [comment]
It's based on your comment
https://github.com/making/yavi/issues/269#issuecomment-1161772306

> I saw the annotation processor but would like to be able not having to annotate the DTO types with validation-specific annotations as I use Yavi to avoid annotations in the first place.
I thought this comment made sense.
And I haven't seen anyone using this feature, and I don't think it provides value for maintenance costs (tests can fail depending on the JDK version).

**Comment by odrotbohm** [comment]
That was more an explanation for why I filed the request. If in doubt, I would like to avoid the string references more than I would like to avoid the annotations. Especially if the latter was only one to be put on a form or DTO type. So yes, the AP is just fine, I think. 🙃

**Comment by making** [comment]
Thank you. User feedback is important. So far, only you have provided feedback on the annotation processor.
It was that I didn't want to use annotations :) So I decided to remove this feature.
If you use the annotation processor, I'll remove the deprecation and create an issue on the class level annotation.

**Comment by odrotbohm** [comment]
Me trying to avoid the annotations, doesn't mean that the APT is not a useful feature to others. So yeah, please keep it around. I'll create a ticket for the type-level annotation.
