### ISSUE TITLE
CustomConstraint of Date

### ISSUE THREAD

**Issue by rogersantos77** [making/yavi#293]
Considering this property of the object to be validated:
`private Date birthDate;`

And this part of the ValidatorBuilder:
`.constraint(MY_OBJ_SAMPLE::getBirthDate, "Birth Date", c -> c
                 .predicate(new dateNotNullConstraint()))`

and dateNotNullConstraint:
```
public class dateNotNullConstraint implements CustomConstraint<Date> {
    @Override
    public String defaultMessageFormat() {
        return "{0} must not be null";
    }

    @Override
    public String messageKey() {
        return "date";
    }

    @Override
    public boolean test(final Date s) {
        return s != null;
    }
}
```

The ValidatorBuilder is not able to validate the constraint... why?

I have Date, Calendar objects... that need to be validated... how do I do it?

**Comment by making** [comment]
`notNull` constraint for any object should be suported
https://yavi.ik.am/#notnull

**Comment by making** [comment]
If you mean supporting more constraints for legacy date objects (like `future`, `past`, `isBefore`, `isAfter`, etc ...), it will never be supported. then use Data and Time APIs instead.

**Comment by rogersantos77** [comment]
Ok... I understood your question, but I need to build some restrictions that validate data... for example "underage" and others... although notNull is not working in my example... it's the simplest that shown.

**Comment by rogersantos77** [comment]
When I talk about these validations I mean that I'm going to make custom constraints, I don't expect the lib to have this, but I'm not managing to evolve with the lib recognizing my properties (Date for example).

**Comment by making** [comment]
Can you share the minimal reproducible example (git repo) ?

**Comment by rogersantos77** [comment]
I'll make it simple for you because today is private

**Comment by making** [comment]
no problem, thanks!

**Comment by making** [comment]
@rogersantos77 let me confirm
> The ValidatorBuilder is not able to validate the constraint... why?

Do you mean that you can't compile the bellow code?
https://github.com/rogersantos77/validator/blob/main/src/main/java/br/com/validator/RegistrationRequestValidator.java#L20-L21

If so, use `_object` instead of `constraints` to avoid ambiguous type inferences as documented bellow
https://yavi.ik.am/#notnull

**Comment by making** [comment]
I'm a bit confused

https://github.com/rogersantos77/validator/blob/main/src/main/java/br/com/validator/constraints/dateNotNullConstraint.java
This implementation (`s == null` for `dateNotNullConstraint`)  is wrong.
The snippet you wrote in the description above (`s != null` for `dateNotNullConstraint`)  is correct.

**Comment by rogersantos77** [comment]
> #If so, use _object instead of constraints to avoid ambiguous type inferences as documented bellow

That's exactly it... I hadn't seen this feature.

> This implementation (s == null for dateNotNullConstraint) is wrong.

About my implementation above... it was my mistake for doing it so fast, sorry. The real error was not compile to use this constraint.
