### ISSUE TITLE
How do I implement List validation in Kotlin?

### ISSUE THREAD

**Issue by otkmnb2783** [making/yavi#30]
How do I implement List validation in Kotlin?

```Kotlin
data class Form(
  val users: List<String>
) {
  companion object {
    val validator = ValidatorBuilder.of(Form::class.java)
       .forEach(GroupCreationRequest::members) {
           ValidatorBuilder.of(String::class.java)
               .konstraint(String::toString) { // <- ★ KProperty Only
                   notEmpty()
               }
               .build()
       }
       .build()
  }
}
```

**Comment by making** [comment]
I'm not sure I get your question.

Does this sample help you?
https://github.com/making/yavi/blob/develop/src/test/kotlin/am/ik/yavi/builder/ValidatorBuilderExtensionsTest.kt#L551

**Comment by otkmnb2783** [comment]
Thank you for an answer.

I want to know how to validate a simple List<String>,
not how to create nested objects.

**Comment by making** [comment]
I think I got you meant.

use `constraint` instead of `konstraint`.
It's up to you how to call the name of the value in a list. 
I would use `value`.

```kotlin
val validator = ValidatorBuilder.of<Form>()
        .forEach(Form::users) {
            constraint(String::toString, "value") { it.greaterThan(1) }
        }
        .build()
```

**Comment by otkmnb2783** [comment]
Thank you for your help.
