### ISSUE TITLE
Apply extra validation on validated object

### ISSUE THREAD

**Issue by ffroliva** [making/yavi#310]
I have an object that is validated and I want to apply another validation after the object is created. Is there a way to avoid having to use the if statement as below? Is there a way to achieve this in a functional style?

```
        Validated<Dataset> validatedDataset
                = Validations.combine(readModel(), readScenario())
                .apply(this::createDataset) 

        if (!validatedDataset.isValid()) {
            return validatedDataset;
        }

        return Validated.of(DATASET_VALIDATOR.validate(validatedDataset.value())
```

Thanks for the help in advance.

**Comment by making** [comment]
Please provide the full minimal reproducible code. I can't determine what you want to do from your fragmented code.

**Comment by making** [comment]
`Validated` means that the object has been validated.
Re-validating a Validated object is a breach of contract.
