### ISSUE TITLE
Unsupported exception: failFast is not Implemented after upgrading to 0.13.0

### ISSUE THREAD

**Issue by Ninglin** [making/yavi#335]
Hi, 

I just bumped yavi from 0.12.1 to 0.13.0 on my project and my unit tests broke with `java.lang.UnsupportedOperationException: failFast is not implemented!`

The builder that's complaining is a builder that has 3 nested validators and two constraintOnCondition.

Is this by design? If so, how can I enable failFast in this new version?

**Comment by making** [comment]
Maybe a bug? 
Can you share the minimal reproducible repo?

**Comment by Ninglin** [comment]
Will set up one and post it here.

**Comment by Ninglin** [comment]
Managed to setup a repro [here](https://github.com/Ninglin/reproYavi-335)

**Comment by making** [comment]
Thanks for sharing. I think I fixed the bug in https://github.com/making/yavi/commit/c7af0e03130a0f36087a9cb086cafc9d68555085

**Comment by Ninglin** [comment]
Any estimate of when this gets released?

**Comment by making** [comment]
@Ninglin 
Would you please test if your sample works with 0.13.1-SNAPSHOT? As soon as I can confirm that, I would like to release 0.13.1.

```xml
    <dependency>
      <groupId>am.ik.yavi</groupId>
      <artifactId>yavi</artifactId>
      <version>0.13.1-SNAPSHOT</version>
    </dependency>
```

```xml
  <repositories>
    <repository>
      <id>snapshot</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
```

**Comment by Ninglin** [comment]
I can confirm that the issue is gone with that version.

**Comment by making** [comment]
Thanks. 0.13.1 is now available on the maven central
