### ISSUE TITLE
feat(): validation involving multiple fields

### ISSUE THREAD

**Issue by davinkevin** [making/yavi#4]
Hi, 

I really like the approach YAVI take to simplify the bean validation, but I would like to know how (and if it is possible simply) we can do a "two field validation"

For example:
```kotlin
data class Foo(val min: Int, val max: Int) // very simple model, can happen on more than two fields with more than one type
```

I would like to be valid only if `min` is smaller than `max`. I don't find anything about it in the current API which is very annoying for me because a huge part of my business domain has this kind of (form) validation on our class.

I find a solution by transforming the value to `Map` then doing the validation on each value... but it's not very efficient (putting into a map and then extracting it)

Thanks for your help

**Comment by making** [comment]
I think [this example](https://github.com/making/yavi/blob/develop/src/test/java/am/ik/yavi/core/CustomValidatorTest.java#L171-L190) is same as your case.

**Comment by making** [comment]
You could simply write like following:

```java
Validator<Foo> validator = Validator.builder(Foo.class).constraintForObject(
			foo -> foo /* or Function.identity() */, "max", c -> c.predicate(foo -> foo.max > foo.min, ViolationMessage.of("max.range", "'max' must be greater than 'min'")))
			.build();
```

**Comment by davinkevin** [comment]
Thanks for the example, I will use that, but it's very verbose to write (even in Kotlin). 

Don't you think this API could be simplified?

**Comment by making** [comment]
Any suggestion?

**Comment by davinkevin** [comment]
I don't know if it's simply possible, but I propose something like this (the name of the method can be changed, I don't have enough imagination 😊)

```kotlin
var validator = Validator.builder(Foo::class.java)
        .constraintGlobal({ foo: Foo -> foo.max > foo.min }, "max", ViolationMessage.of("max.range", "'max' must be greater than 'min'")) })
        .build()
```

I don't know if all the parameters are required here (especially the `max`), but if not, we can remove it.

**Comment by davinkevin** [comment]
You are a machine 👍. Really glad to see this modification in the library. 🎉

**Comment by making** [comment]
will be release in 0.20.0
I really appreciate your feedback
