### ISSUE TITLE
Provide an easy way to override violation default messages per constraint

### ISSUE THREAD

**Issue by making** [making/yavi#6]
Currently there is no way to override a violation message on a constraint.
The only way to override is implementing [`MessageFormatteer`](https://github.com/making/yavi/blob/develop/src/main/java/am/ik/yavi/message/MessageFormatter.java).

It would be convenient if a user can define a customized message on a constraint like following:

``` java
Validator<User> validator = Validator.<User> builder() //
	.constraint(User::getName, "name", c -> c.notNull().message("name is required!") //
				.greaterThanOrEqual(1).message("name is too large!") //
				.lessThanOrEqual(20).message("name is too small!")) //
	.build()
```

It requires some internal logic changes.

**Comment by davinkevin** [comment]
I was about to open this issue... and finally, try to do the work with the Formatter.

Can not wait to see / use this ! 

Yavi is for sure, now, my favorite bean validation system 🤩

**Comment by davinkevin** [comment]
Your proposed API is interesting but we can do something simpler with this:

```java
Validator<User> validator = Validator.<User> builder() //
	.constraint(User::getName, "name", c -> c.notNull().message("name is required!") //
				.greaterThanOrEqual(1, "name is too large!") //
				.lessThanOrEqual(20, "name is too small!")) //
	.build()
```

If you don't like this way of doing, I advice to use JavaPoet to generate this fluent API (https://github.com/square/javapoet)

**Comment by making** [comment]
Thanks, but that adds too many overload methods to maintain ...

**Comment by making** [comment]
I think I've implemented this feature simply in https://github.com/making/yavi/commit/ecd59a0762eca66c00882e28945455c4a04025e1 .
